__title__ = 'fiberhttp'
__description__ = 'High Performance HTTP Requests Library'
__url__ = 'https://www.github.com/xsxo/fiberhttp'
__version__ = '5.0.1'
__author__ = 'xsxo'
__license__ = 'Apache-2.0'
__copyright__ = 'Copyright xsxo'